# Generated by Django 5.2.4 on 2025-08-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.FloatField(help_text='BHK value')),
                ('price_in_rupees', models.FloatField(help_text='Price per BHK')),
                ('bathroom', models.IntegerField(help_text='Number of bathrooms')),
                ('balcony', models.IntegerField(help_text='Number of balconies')),
                ('super_area', models.FloatField(help_text='Super area in sq ft')),
                ('transaction', models.CharField(help_text='Transaction type', max_length=50)),
                ('location', models.CharField(help_text='Property location', max_length=100)),
                ('furnishing', models.CharField(help_text='Furnishing status', max_length=50)),
                ('facing', models.CharField(help_text='Facing direction', max_length=50)),
                ('floor', models.CharField(help_text='Floor details', max_length=100)),
                ('overlooking', models.CharField(help_text='What the property overlooks', max_length=200)),
                ('society', models.CharField(blank=True, help_text='Society/Building name (optional)', max_length=200, null=True)),
                ('prediction_xgboost', models.FloatField(blank=True, null=True)),
                ('prediction_decision_tree', models.FloatField(blank=True, null=True)),
                ('prediction_lgbm', models.FloatField(blank=True, null=True)),
                ('prediction_random_forest', models.FloatField(blank=True, null=True)),
                ('prediction_ridge', models.FloatField(blank=True, null=True)),
                ('prediction_support_vector', models.FloatField(blank=True, null=True)),
                ('prediction_lasso', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
