# Generated by Django 5.2.4 on 2025-08-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyprediction',
            name='prediction_lasso',
        ),
        migrations.RemoveField(
            model_name='propertyprediction',
            name='prediction_ridge',
        ),
    ]
