# Generated by Django 5.2.4 on 2025-08-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_predictor', '0002_remove_ridge_lasso_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyprediction',
            name='prediction_linear_regression',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
