# Generated by Django 5.2.4 on 2025-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
